import { COLLECTIONS, type AppState, type Entity, type JsonValue } from '../../types/domain.ts';
import { PRICE_TABLES, PRICE_VERSION } from './pricing.ts';
import { PROCESS_TEMPLATES, TASK_MODELS } from './templates.ts';
export function makeEntity(data: Record<string,JsonValue>, id: string=crypto.randomUUID(), now=new Date().toISOString()): Entity { return {...data,id,createdAt:now,updatedAt:now}; }
export function createInitialState(organizacaoId='futuro'): AppState {
 const state = Object.fromEntries(COLLECTIONS.map(key=>[key,[]])) as unknown as AppState;
 state.meta={version:1,revision:0,organizacaoId};
 const now=new Date().toISOString();
 const entity=(id:string,data:Record<string,JsonValue>)=>makeEntity(data,id,now);
 state.equipe=[entity('gilmar',{nome:'Gilmar Santos',cargo:'CEO / Sócio',papel:'socio',departamento:'Direção',departamentos:['Fiscal','Pessoal','Contábil','Paralegal e Legalização','Financeiro','Comercial','Administrativo'],crc:'GO-028974/O',status:'Ativo',gestorId:null}),entity('daniel',{nome:'Daniel Branquinho',cargo:'Operações',papel:'operacao',departamento:'Operações',departamentos:['Fiscal','Pessoal','Contábil','Paralegal e Legalização'],status:'Ativo',gestorId:'gilmar'}),entity('tamires',{nome:'Tamires',cargo:'SDR e administrativo',papel:'administrativo',departamento:'Administrativo',departamentos:['Administrativo','Comercial'],status:'Ativo',gestorId:'gilmar'})];
 const services: [string,string,number,string,string,boolean?][]=[['remissao-das','Remissão de guia DAS',5,'por evento','Fiscal'],['remissao-fgts','Remissão de guia FGTS e INSS',10,'por evento','Pessoal'],['nota-nfse','Emissão de NFS-e',10,'por nota','Fiscal'],['nota-nfe','Emissão de NF-e',20,'por nota','Fiscal'],['rescisao-sem-registro','Rescisão de funcionário sem registro',80,'por evento','Pessoal'],['pesquisa-ibge','Pesquisa do IBGE',197,'por evento','Fiscal'],['parcelamento','Parcelamento Simples Nacional, Receita e PGFN',250,'por evento','Fiscal'],['itr','Declaração de ITR',150,'por evento','Fiscal',true],['irpf-simplificada','Declaração de imposto de renda simplificada',150,'por evento','Fiscal'],['irpf-completa','Declaração de imposto de renda completa',200,'por evento','Fiscal',true],['treinamento-administrativo','Treinamento administrativo',180,'por evento','Administrativo'],['conciliacao-cartao','Conciliação de cartão de crédito',250,'por evento','Financeiro']];
 state.servicos=services.map(([id,nome,valor,unidade,departamento,aPartirDe])=>entity(id,{nome,valor,unidade,departamento,aPartirDe:!!aPartirDe,ativo:true,categoria:'Extras e retrabalhos',versao:1,origem:'Escopo fornecido, seção 10',incluidoPlanos:[],historicoPrecos:[{versao:1,valor,vigenteDesde:now}]}));
 state.integracoes=['Z-API','Cora','Alterdata','eContador','NF Stock','Veri','Intermediador de NFS-e','Google Workspace','Assinatura digital'].map((nome,i)=>entity(`integracao-${i}`,{nome,status:'Não configurada',ambiente:'Homologação',observacoes:'Configurar credenciais no cofre e validar conexão antes de usar.'}));
 state.cargos=['Estagiário','Auxiliar','Assistente','Analista','CEO'].map((nome,i)=>entity(`cargo-${i}`,{nome,nivel:nome==='CEO'?'Sócio':nome,departamento:'A definir',salarioMinimo:null,salarioMaximo:null,criteriosPromocao:''}));
 state.metas=[entity('meta-clientes-2026',{nome:'Alcançar 100 clientes ativos',objetivo:'100 ou mais clientes ativos até 31/12/2026',valorMeta:100,indicador:'clientesAtivos',prazo:'2026-12-31',responsavelId:'gilmar',baseHistorica:50,dataBaseHistorica:'2026-09',observacoes:'A base histórica é referência do escopo. O progresso atual usa somente clientes cadastrados.'})];
 const essential=['Armazenamento de XML','Gestão de documentos em nuvem','Acesso por app, plataforma ou e-mail','Suporte por e-mail em até 48h','Treinamento de emissão de nota','Reunião de onboarding','Contabilidade fiscal, pessoal e contábil'];
 const mentor=[...essential.filter(item=>!item.startsWith('Suporte por e-mail')),'Suporte tributário prioritário por WhatsApp','Relatórios gerenciais','Distribuição de lucro com compliance tributário','Programa de indicação','Análise tributária com Fator R','Monitoramento fiscal e CNDs na Veri','Planejamento tributário','Treinamento de gestão financeira','Sistema de gestão financeira','Grupo exclusivo no WhatsApp'];
 state.configuracoes=[
 entity('empresa',{tipo:'empresa',nome:'Futuro Contabilidade Digital',crc:'GO-028974/O',cidade:'Goiânia',uf:'GO'}),
 entity('tabela-precos',{tipo:'precos',nome:'Tabela comercial',versao:PRICE_VERSION,tabelas:JSON.parse(JSON.stringify(PRICE_TABLES)) as JsonValue,industriaDisponivel:false,observacoes:'Indústria e faturamento além da última faixa dependem de parametrização. Tabela comercial, não tributária.'}),
 entity('planos',{tipo:'planos',nome:'Entregáveis por plano',Essencial:essential,Mentor:mentor,'Estratégico':[...mentor,'Reunião mensal de resultados de 1 hora','Análise de precificação','Suporte por telefone','Treinamento de processos','Planejamento financeiro','Escritório virtual incluso']}),
 entity('modelos-tarefas',{tipo:'modelosTarefas',nome:'Modelos de tarefas',modelos:JSON.parse(JSON.stringify(TASK_MODELS)) as JsonValue,orientacao:'Recomendações operacionais do escopo. Confirme a obrigação aplicável e o prazo vigente antes de ativar a recorrência. O sistema não presume prazo legal.'}),
 entity('modelos-processos',{tipo:'modelosProcessos',nome:'Templates de legalização',modelos:JSON.parse(JSON.stringify(PROCESS_TEMPLATES)) as JsonValue}),
 entity('scripts-qualificacao',{tipo:'script',nome:'Perguntas essenciais antes da reunião',conteudo:'CNPJ e regime atual\nFaturamento médio dos últimos 12 meses\nQuantidade de sócios e pró-labore\nFuncionários registrados\nEmissão de notas: quantidade, produto ou serviço\nCertificado digital válido\nContabilidade atual e valor pago\nPrincipal dor\nDébitos ou parcelamentos\nAlvarás e licenças\nPrazo para trocar de contabilidade'}),
 entity('scripts-atendimento',{tipo:'script',nome:'Roteiro de atendimento',conteudo:'1. Responder ao primeiro contato em até 15 minutos.\n2. Fazer as perguntas essenciais.\n3. Registrar respostas no lead.\n4. Classificar por faturamento.\n5. Agendar diagnóstico com data e hora.\n6. Enviar confirmação com link e pauta.\n7. Simular o preço antes da reunião.'}),
 entity('scripts-mensagens',{tipo:'script',nome:'Mensagens de atendimento',conteudo:'PRIMEIRO CONTATO\nOlá! Sou da Futuro Contabilidade Digital. Para entender como podemos ajudar sua empresa, qual é o principal desafio que você quer resolver hoje?\n\nFOLLOW-UP 1\nOlá! Conseguiu avaliar nossa proposta? Posso esclarecer os entregáveis e os próximos passos.\n\nFOLLOW-UP 2\nOlá! Ficou alguma dúvida que esteja impedindo sua decisão? Podemos revisar juntos os pontos mais importantes para sua empresa.\n\nFOLLOW-UP FINAL\nOlá! Vou encerrar este acompanhamento por enquanto. Quando quiser retomar, estarei à disposição.\n\nPROPOSTA NEGADA\nObrigado pelo retorno e pela oportunidade de conhecer sua empresa. Continuamos à disposição.'}),
 entity('scripts-objecoes',{tipo:'script',nome:'Biblioteca de objeções',conteudo:'ESTÁ CARO\nVamos comparar o investimento com o que sua empresa precisa receber. Qual entrega tem mais valor para você?\n\nMEU CONTADOR COBRA MENOS\nEntendo. Podemos conferir juntos o que cada proposta inclui e o acompanhamento de que você precisa.\n\nVOU PENSAR\nClaro. Qual ponto você quer avaliar melhor?\n\nPRECISO FALAR COM MEU SÓCIO\nPodemos marcar uma conversa com vocês dois para esclarecer a proposta.\n\nESTOU SEM TEMPO\nQual horário seria adequado para uma conversa breve?\n\nJÁ TENHO CONTADOR HÁ ANOS\nO que funciona bem hoje e o que você gostaria de melhorar?\n\nNÃO VEJO DIFERENÇA\nVamos olhar o que você recebe hoje e onde precisa de mais apoio.\n\nTEM MULTA PARA SAIR\nVamos conferir juntos as condições do contrato antes da decisão.'}),
 entity('modelos-contratos',{tipo:'contratos',nome:'Modelos de contrato',conteudo:'Importar os modelos aprovados de Prestação de Serviços Profissionais Contábeis e de Consultoria e Assessoria Financeira.',importado:false}),
 entity('personas',{tipo:'personas',nome:'Personas comerciais',itens:['Comércio em Geral','Prestador de Serviço em Geral','Engenheiro PJ','Clínica de Estética','Clínicas em Geral']}),
 entity('jornada-cliente',{tipo:'jornada',nome:'Jornada do cliente',etapas:[{nome:'Boas-vindas',dias:0},{nome:'Onboarding/Implantação',dias:1},{nome:'Ativação',dias:1},{nome:'Acompanhamento Inicial',dias:30},{nome:'Relacionamento',dias:35},{nome:'Fidelização',dias:35},{nome:'Expansão de Serviços',dias:36},{nome:'Pedido de Indicação',dias:37}]}),
 ];
 return state;
}
