import {describe,it,expect} from 'vitest';
import {createInitialState,runCommand,taskSteps,TASK_MODELS} from '../src/services/domain';
import type {Actor,AppState,Command} from '../src/types/domain';
const actor:Actor={id:'gilmar',nome:'Gilmar',papel:'socio',departamentos:[]};
const run=(s:AppState,c:Command)=>runCommand(s,c,actor);
function setup(){let s=run(createInitialState(),{type:'save',collection:'clientes',id:'c',data:{nome:'Teste isolado',origem:'Teste',status:'Ativo',honorario:500,responsavelId:'gilmar',clienteEnviaDocumentos:true,recorrenciasConfirmadas:true,recorrencias:[{modeloId:'coleta',periodicidade:'mensal',responsavelId:'tamires',diaVencimento:10}]}});s=run(s,{type:'generateRecurring',data:{competencia:'2026-09'}});return s;}
describe('Responsáveis e recorrências do cliente',()=>{
 it('preserva responsável atual sem transferência e usa novo responsável na próxima competência',()=>{let s=setup();s=run(s,{type:'save',collection:'clientes',id:'c',data:{recorrencias:[{modeloId:'coleta',periodicidade:'mensal',responsavelId:'daniel',diaVencimento:10}]}});expect(s.tarefas[0].responsavelId).toBe('tamires');s=run(s,{type:'generateRecurring',data:{competencia:'2026-10'}});expect(s.tarefas[1].responsavelId).toBe('daniel');expect(s.clientes[0].clienteEnviaDocumentos).toBe(true);});
 it('transfere pendentes, preserva checklist e histórico concluído',()=>{let s=setup();s=run(s,{type:'generateRecurring',data:{competencia:'2026-10'}});s.tarefas[1].status='Concluída';const steps=structuredClone(s.tarefas[0].passos);s=run(s,{type:'save',collection:'clientes',id:'c',data:{transferirPendentes:true,recorrencias:[{modeloId:'coleta',periodicidade:'mensal',responsavelId:'daniel',diaVencimento:10}]}});expect(s.tarefas[0].responsavelId).toBe('daniel');expect(s.tarefas[0].passos).toEqual(steps);expect(s.tarefas[1].responsavelId).toBe('tamires');expect(s.clientes[0].transferirPendentes).toBeUndefined();expect(s.atividades.some(a=>a.acao==='responsável transferido')).toBe(true);});
 it('rejeita responsável inexistente sem modificar o estado original',()=>{const s=setup();expect(()=>run(s,{type:'save',collection:'clientes',id:'c',data:{transferirPendentes:true,recorrencias:[{modeloId:'coleta',periodicidade:'mensal',responsavelId:'inexistente',diaVencimento:10}]}})).toThrow();expect(s.tarefas[0].responsavelId).toBe('tamires');});
 it('todos os modelos têm checklist executável',()=>{for(const model of TASK_MODELS){const steps=taskSteps(model.id);expect(steps.length).toBeGreaterThan(2);expect(steps.every(s=>s.obrigatorio&&!s.concluido)).toBe(true);}});
});