import { useState, type FormEvent } from 'react';
import { Plus, Search, Scale, ArrowRight, LockKeyhole, CalendarDays, CheckCircle2, Pencil, FileCheck2 } from 'lucide-react';
import { useApp } from '../hooks/useApp';
import { PROCESS_TEMPLATES, createProcessStages } from '../services/domain';
import type { Entity, JsonValue, Stage } from '../types/domain';
import StepChecklist from '../components/workflows/StepChecklist';
import { WorkflowDialog, FormField, TeamSelect, ClientSelect, FormActions, FieldError, EmptyWorkflow, ProgressBar, WorkflowToolbar, text, number, today, dateLabel, money, recordName, listSteps, formValues, inputText, inputNumber } from '../components/workflows/WorkflowUi';

function stagesOf(item: Entity): Stage[] { return Array.isArray(item.etapas) ? item.etapas.filter((stage): stage is Stage => typeof stage === 'object' && stage !== null && !Array.isArray(stage) && Array.isArray(stage.itens) && typeof stage.nome === 'string') : []; }

function ProcessForm({ process, onClose }: { process?: Entity; onClose: () => void }) {
  const { state, actor, execute, busy } = useApp();
  const [templateId, setTemplateId] = useState(text(process?.templateId) || 'abertura');
  const [error, setError] = useState('');
  const template = PROCESS_TEMPLATES.find(item => item.id === templateId);
  const save = async (event: FormEvent<HTMLFormElement>) => { const form = formValues(event); const data: Record<string, JsonValue> = { nome: inputText(form, 'nome') || template?.nome || '', templateId, tipo: template?.nome || '', clienteId: inputText(form, 'clienteId'), responsavelId: inputText(form, 'responsavelId'), prazo: inputText(form, 'prazo'), valorServico: inputNumber(form, 'valorServico'), valorPago: inputNumber(form, 'valorPago'), observacoes: inputText(form, 'observacoes'), departamento: 'Paralegal e Legalização' }; if (!process) { data.etapas = createProcessStages(templateId); data.etapaAtual = 0; data.status = 'Em andamento'; } try { await execute({ type: 'save', collection: 'processos', ...(process ? { id: process.id } : {}), data }); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível salvar o processo.'); } };
  return <WorkflowDialog title={process ? 'Editar processo' : 'Novo processo'} onClose={onClose}><form onSubmit={save}><div className="wf-grid"><FormField label="Tipo de processo" full><select value={templateId} disabled={Boolean(process)} onChange={event => setTemplateId(event.target.value)}>{PROCESS_TEMPLATES.map(item => <option key={item.id} value={item.id}>{item.nome}</option>)}</select></FormField><FormField label="Identificação do processo" full><input name="nome" defaultValue={text(process?.nome)} placeholder={template?.nome}/></FormField><FormField label="Cliente"><ClientSelect clients={state.clientes} value={text(process?.clienteId)}/></FormField><FormField label="Responsável"><TeamSelect team={state.equipe} value={text(process?.responsavelId) || actor.memberId || actor.id}/></FormField><FormField label="Prazo interno"><input name="prazo" type="date" required defaultValue={text(process?.prazo) || today()}/></FormField><FormField label="Valor do serviço (R$)"><input name="valorServico" type="number" min="0" step="0.01" required defaultValue={text(process?.valorServico)}/></FormField><FormField label="Valor já pago (R$)" help="Registre somente o valor efetivamente confirmado."><input name="valorPago" type="number" min="0" step="0.01" defaultValue={text(process?.valorPago) || '0'}/></FormField><FormField label="Observações" full><textarea name="observacoes" defaultValue={text(process?.observacoes)} placeholder="Detalhes, protocolos e particularidades do cliente."/></FormField>{!process && template ? <div className="wf-note wf-span"><strong>{template.blocos.length} etapas com verificação obrigatória</strong><br/>{template.blocos.map(block => block.nome).join(' → ')}<br/>Cada etapa só avança depois da conclusão dos itens obrigatórios.</div> : null}</div><FieldError error={error}/><FormActions busy={busy} label={process ? 'Salvar alterações' : 'Abrir processo'} onClose={onClose}/></form></WorkflowDialog>;
}

function ProcessDetail({ id, onClose, onEdit }: { id: string; onClose: () => void; onEdit: (process: Entity) => void }) {
  const { state, execute, uploadDocument, busy } = useApp();
  const process = state.processos.find(item => item.id === id);
  const [error, setError] = useState('');
  const [uploading, setUploading] = useState(false);
  if (!process) return null;
  const stages = stagesOf(process);
  const current = number(process.etapaAtual);
  const completed = text(process.status) === 'Concluído';
  const stage = stages[Math.min(current, stages.length - 1)];
  const steps = stage ? listSteps(stage.itens) : [];
  const pending = steps.filter(item => item.obrigatorio && !item.concluido).length;
  const license = ['alvara', 'certificado'].includes(text(process.templateId));
  const save = async (data: Record<string, JsonValue>) => { await execute({ type: 'save', collection: 'processos', id: process.id, data }); };
  return <WorkflowDialog title={text(process.nome || process.tipo)} onClose={onClose} wide><div className="wf-detail-grid"><section><div className="wf-inline-actions"><span className={`wf-pill ${completed ? '' : 'wf-pill-gold'}`}>{text(process.status)}</span><span className="wf-muted">{recordName(state.clientes, process.clienteId)}</span></div><h3 style={{ fontSize: 21, marginBottom: 8, marginTop: 24 }}>{completed ? 'Processo concluído' : stage?.nome || 'Etapas do processo'}</h3><p className="wf-help-block">{completed ? 'As etapas foram concluídas e o registro está disponível no histórico.' : `Etapa ${current + 1} de ${stages.length}. ${pending ? `${pending} itens obrigatórios para liberar o avanço.` : 'Todos os itens obrigatórios desta etapa estão concluídos.'}`}</p><ProgressBar done={steps.filter(item => item.concluido).length} total={steps.length}/><StepChecklist item={process} collection="processos" steps={steps} execute={execute} uploadDocument={uploadDocument} busy={busy} stageIndex={current} locked={completed}/>
    {license && !completed ? <form onSubmit={async event => { const form = formValues(event); try { await save({ validade: inputText(form, 'validade'), nomeLicenca: inputText(form, 'nomeLicenca') }); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao salvar dados da emissão.'); } }}><hr className="wf-line"/><h3 className="wf-section-title">Documento emitido e validade</h3><p className="wf-help-block">Ao concluir, o documento e sua validade serão vinculados à ficha do cliente.</p><div className="wf-grid"><FormField label="Nome da licença ou certificado"><input name="nomeLicenca" required defaultValue={text(process.nomeLicenca) || text(process.tipo)}/></FormField><FormField label="Válido até"><input name="validade" type="date" required defaultValue={text(process.validade)}/></FormField><FormField label="Documento emitido" full><input type="file" disabled={busy || uploading} onChange={async event => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); try { const doc = await uploadDocument(file, { nome: file.name, clienteId: text(process.clienteId), departamento: 'Paralegal e Legalização', processoId: process.id }); await save({ documentoId: doc.id }); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao anexar o documento.'); } finally { setUploading(false); } }}/><small>{uploading ? 'Salvando documento…' : text(process.documentoId) ? 'Documento salvo e vinculado.' : 'O documento é obrigatório para a conclusão.'}</small></FormField></div><button className="button button-secondary" style={{ marginTop: 15 }} disabled={busy || uploading}>Salvar dados da emissão</button></form> : null}
    <FieldError error={error}/><footer className="wf-actions">{completed ? <span className="wf-pill"><CheckCircle2 size={14}/>Finalizado em {dateLabel(process.concluidoEm || process.updatedAt)}</span> : <button className="button button-primary" disabled={busy || uploading} onClick={async () => { try { await execute({ type: 'advanceProcess', id: process.id }); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Verifique os itens pendentes.'); } }}><ArrowRight size={16}/>{current === stages.length - 1 ? 'Concluir processo' : 'Concluir etapa e avançar'}</button>}</footer>
  </section><aside className="wf-detail-aside"><h3>Jornada do processo</h3><div className="wf-step-nav">{stages.map((item, index) => <div key={item.id} className={index === current && !completed ? 'is-current' : index < current || completed ? 'is-past' : ''}>{index + 1}. {item.nome}<small>{index < current || completed ? 'Etapa concluída' : index === current ? 'Etapa atual' : 'Aguardando etapa anterior'}</small></div>)}</div><div className="wf-price-line"><span>Responsável</span><strong>{recordName(state.equipe, process.responsavelId)}</strong></div><div className="wf-price-line"><span>Prazo</span><strong>{dateLabel(process.prazo)}</strong></div><div className="wf-price-line"><span>Valor do serviço</span><strong>{money(process.valorServico)}</strong></div><div className="wf-price-line"><span>Pago</span><strong>{money(process.valorPago)}</strong></div>{!completed ? <button className="button button-secondary" style={{ marginTop: 18 }} onClick={() => onEdit(process)}><Pencil size={13}/>Editar dados</button> : null}{text(process.observacoes) ? <p className="wf-help-block" style={{ marginTop: 18 }}>{text(process.observacoes)}</p> : null}<p className="wf-muted" style={{ marginTop: 22 }}><LockKeyhole size={12} style={{ display: 'inline', marginRight: 5 }}/>Os avanços são validados e registrados no histórico.</p></aside></div></WorkflowDialog>;
}

function ProcessCard({ process, state, onOpen }: { process: Entity; state: ReturnType<typeof useApp>['state']; onOpen: () => void }) {
  const stages = stagesOf(process);
  const index = number(process.etapaAtual);
  const completed = text(process.status) === 'Concluído';
  const steps = listSteps(stages[Math.min(index, stages.length - 1)]?.itens);
  const late = !completed && text(process.prazo) < today();
  return <article className="wf-process-card"><div className="wf-inline-actions" style={{ justifyContent: 'space-between' }}><span className={`wf-pill ${late ? 'wf-pill-red' : completed ? '' : 'wf-pill-gold'}`}>{late ? 'Prazo vencido' : text(process.status)}</span><Scale size={16} color="#9cae98"/></div><div><h3>{text(process.nome || process.tipo)}</h3><p>{recordName(state.clientes, process.clienteId)}</p></div><div className="wf-process-step">{completed ? 'Todas as etapas concluídas' : `${index + 1}. ${stages[index]?.nome || 'Etapa inicial'}`}</div><ProgressBar done={steps.filter(step => step.concluido).length} total={steps.length}/><div className="wf-inline-actions" style={{ justifyContent: 'space-between' }}><span className="wf-muted">{recordName(state.equipe, process.responsavelId)}</span><span className="wf-muted"><CalendarDays size={11} style={{ display: 'inline', marginRight: 4 }}/>{dateLabel(process.prazo)}</span></div><div className="wf-process-card-footer"><strong style={{ fontSize: 13, color: '#385f51' }}>{money(process.valorServico)}</strong><button className="button button-secondary" onClick={onOpen}>Abrir checklist<ArrowRight size={13}/></button></div></article>;
}

export default function ProcessesPage() {
  const { state } = useApp();
  const [templateId, setTemplateId] = useState('');
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('');
  const [responsible, setResponsible] = useState('');
  const [newProcess, setNewProcess] = useState(false);
  const [selected, setSelected] = useState<string | null>(null);
  const [editing, setEditing] = useState<Entity | undefined>();
  const pending = state.processos.filter(item => text(item.status) !== 'Concluído');
  const rows = state.processos.filter(item => (!templateId || text(item.templateId) === templateId) && (!status || text(item.status) === status) && (!responsible || text(item.responsavelId) === responsible) && `${text(item.nome)} ${recordName(state.clientes, item.clienteId)}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))).sort((a, b) => text(a.prazo).localeCompare(text(b.prazo)));
  const template = PROCESS_TEMPLATES.find(item => item.id === templateId);
  return <div><header className="page-header"><div><span className="wf-eyebrow">DA ABERTURA À INTEGRAÇÃO</span><h1>Legalização</h1><p>Processos organizados, documentos conferidos e cada etapa registrada.</p></div><button className="button button-primary" onClick={() => setNewProcess(true)}><Plus size={17}/>Novo processo</button></header><div className="wf-stats"><div className="wf-stat"><span>Em andamento</span><strong>{pending.length}</strong><small>Processos abertos</small></div><div className="wf-stat"><span>Prazo vencido</span><strong>{pending.filter(item => text(item.prazo) < today()).length}</strong><small>Exigem acompanhamento</small></div><div className="wf-stat"><span>Onboarding</span><strong>{pending.filter(item => text(item.templateId) === 'onboarding').length}</strong><small>Clientes em integração</small></div><div className="wf-stat"><span>Concluídos</span><strong>{state.processos.length - pending.length}</strong><small>Jornadas finalizadas</small></div></div>
    <WorkflowToolbar><label className="wf-search"><Search size={16}/><input aria-label="Buscar processo ou cliente" placeholder="Buscar processo ou cliente" value={query} onChange={event => setQuery(event.target.value)}/></label><select aria-label="Filtrar tipo de processo" value={templateId} onChange={event => setTemplateId(event.target.value)}><option value="">Todos os processos</option>{PROCESS_TEMPLATES.map(item => <option key={item.id} value={item.id}>{item.nome}</option>)}</select><select aria-label="Filtrar status" value={status} onChange={event => setStatus(event.target.value)}><option value="">Todos os status</option><option>Em andamento</option><option>Concluído</option></select><select aria-label="Filtrar responsável" value={responsible} onChange={event => setResponsible(event.target.value)}><option value="">Todos os responsáveis</option>{state.equipe.map(item => <option key={item.id} value={item.id}>{text(item.nome)}</option>)}</select></WorkflowToolbar>
    {rows.length ? template ? <div className="wf-kanban" style={{ gridAutoColumns: 306 }}>{[...template.blocos.map(item => item.nome), 'Concluídos'].map((name, index) => { const stageRows = rows.filter(item => text(item.status) === 'Concluído' ? index === template.blocos.length : number(item.etapaAtual) === index); return <section className="wf-kanban-column" key={name}><div className="wf-kanban-heading">{index + 1}. {name}<span>{stageRows.length}</span></div>{stageRows.map(item => <div key={item.id} style={{ marginBottom: 12 }}><ProcessCard process={item} state={state} onOpen={() => setSelected(item.id)}/></div>)}{!stageRows.length ? <div className="wf-column-empty">Nenhum processo nesta etapa</div> : null}</section>; })}</div> : <div className="wf-process-board">{rows.map(item => <ProcessCard key={item.id} process={item} state={state} onOpen={() => setSelected(item.id)}/>)}</div> : <div className="card"><EmptyWorkflow icon={<FileCheck2 size={26}/>} title={state.processos.length ? 'Nenhum processo com estes filtros' : 'Cada etapa no lugar certo'} description={state.processos.length ? 'Altere a busca ou os filtros para encontrar outros processos.' : 'Abra um processo com checklist pronto de abertura, alteração, baixa, alvará, certificado ou onboarding.'}><button className="button button-primary" onClick={() => setNewProcess(true)}><Plus size={15}/>Abrir primeiro processo</button></EmptyWorkflow></div>}
    {newProcess || editing ? <ProcessForm process={editing} onClose={() => { setNewProcess(false); setEditing(undefined); }}/> : null}{selected && !editing ? <ProcessDetail id={selected} onClose={() => setSelected(null)} onEdit={setEditing}/> : null}
  </div>;
}
