import { useState, type FormEvent } from 'react';
import { Plus, Search, ListChecks, CalendarDays, CheckCircle2, RefreshCw, Clock3, Pencil } from 'lucide-react';
import { useApp } from '../hooks/useApp';
import { TASK_MODELS, taskSteps, recommendRecurrences } from '../services/domain';
import type { Entity, JsonValue } from '../types/domain';
import StepChecklist from '../components/workflows/StepChecklist';
import { WorkflowDialog, FormField, TeamSelect, ClientSelect, FormActions, FieldError, EmptyWorkflow, ProgressBar, WorkflowToolbar, text, number, today, month, dateLabel, recordName, listSteps, formValues, inputText, departments } from '../components/workflows/WorkflowUi';

const tabs = [{ id: 'mensal', label: 'Mensais' }, { id: 'trimestral', label: 'Trimestrais' }, { id: 'anual', label: 'Anuais' }, { id: 'avulsa', label: 'Avulsas' }, { id: 'minha', label: 'Minha mesa' }, { id: 'todas', label: 'Todas' }];
const demandTypes = ['Consulta e orientação', 'Admissão', 'Demissão', 'Férias', 'Folha de pagamento', 'Imposto e guia', 'Nota fiscal', 'Documento e certidão', 'Alteração cadastral', 'Legalização', 'Cobrança', 'Follow-up comercial', 'Reunião', 'Outros'];

function TaskForm({ task, onClose }: { task?: Entity; onClose: () => void }) {
  const { state, execute, busy, actor } = useApp();
  const [modelId, setModelId] = useState(text(task?.modeloId));
  const [error, setError] = useState('');
  const model = TASK_MODELS.find(item => item.id === modelId);
  const save = async (event: FormEvent<HTMLFormElement>) => {
    const form = formValues(event);
    const clientId = inputText(form, 'clienteId');
    const client = state.clientes.find(item => item.id === clientId);
    const custom = inputText(form, 'passos').split('\n').map(item => item.trim()).filter(Boolean);
    const data: Record<string, JsonValue> = { nome: inputText(form, 'nome') || model?.nome || '', clienteId: clientId, tipoDemanda: inputText(form, 'tipoDemanda'), departamento: inputText(form, 'departamento'), responsavelId: inputText(form, 'responsavelId'), prazo: inputText(form, 'prazo'), competencia: inputText(form, 'competencia'), prioridade: inputText(form, 'prioridade'), descricao: inputText(form, 'descricao'), status: task ? text(task.status) : 'Pendente', modeloId: modelId, periodicidade: model?.periodicidade || 'avulsa' };
    if (!task) { data.passos = model ? taskSteps(modelId, client) : custom.map((descricao, index) => ({ id: `passo-${index + 1}`, descricao, obrigatorio: true, concluido: false, natureza: 'marcar' })); data.exigeProtocolo = model?.exigeProtocolo || false; }
    try { await execute({ type: 'save', collection: 'tarefas', ...(task ? { id: task.id } : {}), data }); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível salvar a tarefa.'); }
  };
  return <WorkflowDialog title={task ? 'Editar tarefa' : 'Nova tarefa'} onClose={onClose}><form onSubmit={save}><div className="wf-grid">
    {!task ? <FormField label="Modelo de tarefa" full><select value={modelId} onChange={event => setModelId(event.target.value)}><option value="">Tarefa avulsa personalizada</option>{TASK_MODELS.map(item => <option key={item.id} value={item.id}>{item.nome} · {item.periodicidade}</option>)}</select></FormField> : null}
    <FormField label="Nome da tarefa" full><input name="nome" required={!model} defaultValue={text(task?.nome)} placeholder={model?.nome || 'Ex.: Conferir documentos recebidos'}/></FormField>
    <FormField label="Cliente"><ClientSelect clients={state.clientes} value={text(task?.clienteId)} required={true}/></FormField>
    <FormField label="Tipo de demanda"><select name="tipoDemanda" defaultValue={text(task?.tipoDemanda) || 'Consulta e orientação'}>{demandTypes.map(value => <option key={value}>{value}</option>)}</select></FormField>
    <FormField label="Departamento"><select name="departamento" key={modelId} defaultValue={text(task?.departamento) || model?.departamento || 'Administrativo'}>{departments.map(value => <option key={value}>{value}</option>)}</select></FormField>
    <FormField label="Responsável"><TeamSelect team={state.equipe} value={text(task?.responsavelId) || actor.memberId || actor.id}/></FormField>
    <FormField label="Prazo"><input name="prazo" type="date" required defaultValue={text(task?.prazo) || today()}/></FormField>
    <FormField label="Competência"><input name="competencia" type="month" required defaultValue={text(task?.competencia) || month()}/></FormField>
    <FormField label="Prioridade"><select name="prioridade" defaultValue={text(task?.prioridade) || 'Normal'}><option>Baixa</option><option>Normal</option><option>Alta</option><option>Urgente</option></select></FormField>
    <FormField label="Orientações" full><textarea name="descricao" defaultValue={text(task?.descricao)} placeholder="Descreva o que deve ser feito e o resultado esperado."/></FormField>
    {!task && !model ? <FormField label="Passos para concluir" help="Um passo por linha. Os itens serão obrigatórios para finalizar a tarefa." full><textarea name="passos" required defaultValue="Executar a solicitação&#10;Conferir o resultado&#10;Registrar a entrega"/></FormField> : null}
    {model ? <div className="wf-note wf-span"><strong>{model.passos.length} passos do modelo</strong><br/>{model.passos.slice(0, 3).join(' · ')}{model.passos.length > 3 ? '…' : ''}<br/>{model.exigeProtocolo ? 'A conclusão exige protocolo e recibo.' : 'A conclusão exige todos os passos obrigatórios.'}</div> : null}
  </div><FieldError error={error}/><FormActions busy={busy} label={task ? 'Salvar alterações' : 'Criar tarefa'} onClose={onClose}/></form></WorkflowDialog>;
}

function RecurringForm({ onClose }: { onClose: () => void }) {
  const { state, execute, busy } = useApp();
  const [clientId, setClientId] = useState('');
  const [error, setError] = useState('');
  const client = state.clientes.find(item => item.id === clientId);
  const rules = client && Array.isArray(client.recorrencias) ? client.recorrencias.filter(item => typeof item === 'object' && item !== null && !Array.isArray(item)) : [];
  const recommendations = client ? recommendRecurrences(client) : [];
  return <WorkflowDialog title="Gerar tarefas da competência" onClose={onClose}><form onSubmit={async event => { const form = formValues(event); try { await execute({ type: 'generateRecurring', data: { competencia: inputText(form, 'competencia'), ...(clientId ? { clienteId: clientId } : {}) } }); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível gerar as tarefas.'); } }}><p className="wf-help-block">Gera as tarefas das regras já revisadas no cadastro do cliente. Tarefas da mesma competência e modelo não são duplicadas.</p><div className="wf-grid"><FormField label="Cliente"><select required value={clientId} onChange={event => setClientId(event.target.value)}><option value="">Selecione um cliente</option>{state.clientes.filter(item => text(item.status) === 'Ativo').map(item => <option key={item.id} value={item.id}>{text(item.razaoSocial || item.nome)}</option>)}</select></FormField><FormField label="Competência"><input type="month" name="competencia" defaultValue={month()} required/></FormField></div>{client ? <div className="wf-note" style={{ marginTop: 18 }}><strong>{rules.length} regras cadastradas</strong><br/>{recommendations.length} modelos sugeridos conforme os dados atuais. Revise aplicabilidade, responsável e prazos na ficha do cliente antes de gerar.</div> : null}<FieldError error={error}/><FormActions busy={busy} label="Gerar competência" onClose={onClose}/></form></WorkflowDialog>;
}

function TaskDetail({ id, onClose, onEdit }: { id: string; onClose: () => void; onEdit: (task: Entity) => void }) {
  const { state, execute, uploadDocument, busy } = useApp();
  const task = state.tarefas.find(item => item.id === id);
  const [error, setError] = useState('');
  const [timerStart, setTimerStart] = useState<number | null>(null);
  if (!task) return null;
  const steps = listSteps(task.passos);
  const completed = text(task.status) === 'Concluída';
  const done = steps.filter(step => step.concluido).length;
  const save = async (data: Record<string, JsonValue>) => { try { await execute({ type: 'save', collection: 'tarefas', id: task.id, data }); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível salvar.'); } };
  return <WorkflowDialog title={text(task.nome)} onClose={onClose} wide><div className="wf-detail-grid"><section><div className="wf-inline-actions"><span className={`wf-pill ${!completed && text(task.prazo) < today() ? 'wf-pill-red' : ''}`}>{text(task.status)}</span><span className="wf-muted">{text(task.departamento)} · {dateLabel(task.prazo)}</span></div>{text(task.descricao) ? <p className="wf-help-block" style={{ marginTop: 20 }}>{text(task.descricao)}</p> : null}<h3 className="wf-section-title" style={{ marginTop: 25 }}>Checklist da entrega</h3><ProgressBar done={done} total={steps.length}/><StepChecklist item={task} collection="tarefas" steps={steps} execute={execute} uploadDocument={uploadDocument} busy={busy} locked={completed}/>{!steps.length ? <p className="wf-note">Esta tarefa não possui passos. Revise a descrição antes de finalizar.</p> : null}
    {!completed ? <form onSubmit={async event => { const form = formValues(event); await save({ protocolo: inputText(form, 'protocolo'), ...(inputText(form, 'justificativaColeta') ? {justificativaColeta: inputText(form, 'justificativaColeta'), status:'Justificada'} : {}) }); }}><div className="wf-grid"><FormField label={task.exigeProtocolo ? 'Protocolo da obrigação' : 'Protocolo ou referência'} full><input name="protocolo" defaultValue={text(task.protocolo)}/></FormField>{text(task.modeloId) === 'coleta' ? <FormField label="Justificativa para dispensar coleta" help="A justificativa libera os fechamentos dependentes e fica registrada. Informe pelo menos 10 caracteres." full><textarea name="justificativaColeta" minLength={10} defaultValue={text(task.justificativaColeta)}/></FormField> : null}<label className="wf-field wf-span"><span>Recibo ou comprovante de entrega</span><input type="file" disabled={busy} onChange={async event => { const file = event.target.files?.[0]; if (!file) return; try { const doc = await uploadDocument(file, { clienteId: text(task.clienteId), departamento: text(task.departamento), nome: file.name, tarefaId: task.id }); await save({ reciboId: doc.id }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Falha ao salvar o recibo.'); } }}/>{text(task.reciboId) ? <small>Recibo salvo e vinculado à tarefa.</small> : null}</label></div><button className="button button-secondary" style={{ marginTop: 16 }} disabled={busy}>Salvar protocolo e observações</button></form> : null}
    <FieldError error={error}/><footer className="wf-actions">{!completed ? <button type="button" className="button button-primary" disabled={busy} onClick={async () => { try { await execute({ type: 'completeTask', id: task.id }); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Há itens pendentes.'); } }}><CheckCircle2 size={16}/>Concluir tarefa</button> : <span className="wf-pill"><CheckCircle2 size={14}/>Entrega concluída</span>}</footer>
  </section><aside className="wf-detail-aside"><h3>Resumo da tarefa</h3><div className="wf-price-line"><span>Cliente</span><strong>{recordName(state.clientes, task.clienteId)}</strong></div><div className="wf-price-line"><span>Responsável</span><strong>{recordName(state.equipe, task.responsavelId)}</strong></div><div className="wf-price-line"><span>Competência</span><strong>{text(task.competencia)}</strong></div><div className="wf-price-line"><span>Prioridade</span><strong>{text(task.prioridade) || 'Normal'}</strong></div><div className="wf-price-line"><span>Tempo registrado</span><strong>{number(task.minutosRegistrados)} min</strong></div>{!completed ? <><button type="button" className="button button-secondary" style={{ marginTop: 18 }} disabled={busy} onClick={() => onEdit(task)}><Pencil size={14}/>Editar tarefa</button><button type="button" className="button button-secondary" style={{ marginTop: 10 }} disabled={busy} onClick={async () => { if (timerStart === null) { setTimerStart(Date.now()); return; } const minutes = Math.max(1, Math.ceil((Date.now() - timerStart) / 60000)); try { await execute({ type: 'save', collection: 'tarefas', id: task.id, data: { minutosRegistrados: number(task.minutosRegistrados) + minutes } }); setTimerStart(null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível registrar o tempo.'); } }}><Clock3 size={14}/>{timerStart === null ? 'Iniciar cronômetro' : 'Parar e registrar tempo'}</button>{timerStart !== null ? <p className="wf-muted">Cronômetro iniciado. Pare para salvar antes de fechar esta janela.</p> : null}</> : null}<p className="wf-muted" style={{ marginTop: 23 }}>A conclusão é validada pelo sistema. Passos obrigatórios e comprovantes precisam estar registrados.</p></aside></div></WorkflowDialog>;
}

export default function TasksPage() {
  const { state, actor } = useApp();
  const [tab, setTab] = useState('mensal');
  const [query, setQuery] = useState('');
  const [competence, setCompetence] = useState(month());
  const [department, setDepartment] = useState('');
  const [responsible, setResponsible] = useState('');
  const [clientId, setClientId] = useState('');
  const [dialog, setDialog] = useState<'new' | 'recurring' | null>(null);
  const [selected, setSelected] = useState<string | null>(null);
  const [editing, setEditing] = useState<Entity | undefined>();
  const pending = state.tarefas.filter(task => text(task.status) !== 'Concluída');
  const overdue = pending.filter(task => text(task.prazo) && text(task.prazo) < today());
  const mine = (task: Entity) => [actor.id, actor.memberId].includes(text(task.responsavelId));
  const rows = state.tarefas.filter(task => (tab === 'todas' || (tab === 'minha' ? mine(task) : (text(task.periodicidade) || 'avulsa') === tab)) && (!competence || text(task.competencia) === competence) && (!department || text(task.departamento) === department) && (!responsible || text(task.responsavelId) === responsible) && (!clientId || text(task.clienteId) === clientId) && `${text(task.nome)} ${recordName(state.clientes, task.clienteId)}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))).sort((a, b) => text(a.prazo).localeCompare(text(b.prazo)));
  return <div><header className="page-header"><div><span className="wf-eyebrow">OPERAÇÃO EM DIA</span><h1>Tarefas</h1><p>Do recebimento dos documentos à entrega ao cliente.</p></div><div className="wf-inline-actions"><button className="button button-secondary" onClick={() => setDialog('recurring')}><RefreshCw size={16}/>Gerar competência</button><button className="button button-primary" onClick={() => setDialog('new')}><Plus size={17}/>Nova tarefa</button></div></header>
    <div className="wf-stats"><div className="wf-stat"><span>Pendentes</span><strong>{pending.length}</strong><small>Em toda a operação</small></div><div className="wf-stat"><span>Em atraso</span><strong style={{ color: overdue.length ? '#a44e41' : undefined }}>{overdue.length}</strong><small>Precisam de atenção</small></div><div className="wf-stat"><span>Minha mesa</span><strong>{pending.filter(mine).length}</strong><small>Sob sua responsabilidade</small></div><div className="wf-stat"><span>Concluídas no mês</span><strong>{state.tarefas.filter(task => text(task.status) === 'Concluída' && text(task.competencia) === month()).length}</strong><small>Competência {month().split('-').reverse().join('/')}</small></div></div>
    <div className="wf-tabs" role="tablist" aria-label="Visões de tarefas">{tabs.map(item => <button key={item.id} role="tab" aria-selected={tab === item.id} onClick={() => setTab(item.id)}>{item.label}</button>)}</div>
    <WorkflowToolbar><label className="wf-search"><Search size={16}/><input aria-label="Buscar tarefa ou cliente" value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar tarefa ou cliente"/></label><input aria-label="Competência" type="month" value={competence} onChange={event => setCompetence(event.target.value)}/><select aria-label="Filtrar departamento" value={department} onChange={event => setDepartment(event.target.value)}><option value="">Todos os departamentos</option>{departments.map(value => <option key={value}>{value}</option>)}</select><select aria-label="Filtrar responsável" value={responsible} onChange={event => setResponsible(event.target.value)}><option value="">Todos os responsáveis</option>{state.equipe.map(item => <option key={item.id} value={item.id}>{text(item.nome)}</option>)}</select><select aria-label="Filtrar cliente" value={clientId} onChange={event => setClientId(event.target.value)}><option value="">Todos os clientes</option>{state.clientes.map(item => <option key={item.id} value={item.id}>{text(item.razaoSocial || item.nome)}</option>)}</select></WorkflowToolbar>
    <div className="wf-mobile-scroll">{rows.length ? <table className="wf-table"><thead><tr><th>Tarefa / cliente</th><th>Responsável</th><th>Prazo</th><th>Checklist</th><th>Status</th><th/></tr></thead><tbody>{rows.map(task => { const steps = listSteps(task.passos); const late = text(task.status) !== 'Concluída' && text(task.prazo) < today(); return <tr key={task.id}><td><button className="wf-table-row-button" onClick={() => setSelected(task.id)}><strong>{text(task.nome)}</strong><small>{recordName(state.clientes, task.clienteId)} · {text(task.departamento)}</small></button></td><td>{recordName(state.equipe, task.responsavelId)}</td><td><span className={`wf-pill ${late ? 'wf-pill-red' : ''}`}><CalendarDays size={11}/>{dateLabel(task.prazo)}</span></td><td><ProgressBar done={steps.filter(step => step.concluido).length} total={steps.length}/><small>{steps.find(step => !step.concluido)?.descricao || 'Passos concluídos'}</small></td><td><span className={`wf-pill ${late ? 'wf-pill-red' : text(task.status) === 'Concluída' ? '' : 'wf-pill-gold'}`}>{text(task.status)}</span></td><td><button className="button button-secondary" onClick={() => setSelected(task.id)}>Abrir</button></td></tr>; })}</tbody></table> : <EmptyWorkflow icon={<ListChecks size={26}/>} title={state.tarefas.length ? 'Nenhuma tarefa nesta visão' : 'Organize a primeira entrega'} description={state.tarefas.length ? 'Ajuste a competência ou os filtros para encontrar outras tarefas.' : 'Cadastre uma tarefa avulsa ou gere a competência a partir das regras dos clientes.'}><button className="button button-primary" onClick={() => setDialog('new')}><Plus size={15}/>Criar tarefa</button></EmptyWorkflow>}</div>
    {dialog === 'new' || editing ? <TaskForm task={editing} onClose={() => { setDialog(null); setEditing(undefined); }}/>: null}{dialog === 'recurring' ? <RecurringForm onClose={() => setDialog(null)}/> : null}{selected && !editing ? <TaskDetail id={selected} onClose={() => setSelected(null)} onEdit={setEditing}/> : null}
  </div>;
}


