import {reconcileRecurrences} from '../services/recurrenceSelection';
import {useState,useRef,useEffect} from 'react';
import type {Entity,JsonValue} from '../types/domain';
import {TASK_MODELS,recommendRecurrences,taskSteps} from '../services/domain';
import {records,text} from '../utils/records';
export default function RecurrenceEditor({value,profile,team,responsible,onChange}:{value:JsonValue|undefined;profile:Record<string,unknown>;team:Entity[];responsible:string;onChange:(rules:Record<string,JsonValue>[])=>void}){
 const [query,setQuery]=useState('');const rules=records(value);const suggested=new Set(recommendRecurrences(profile).map(r=>r.modeloId));
 const previous=useRef<string[]|null>(null);const excluded=useRef<string[]>([]);const signature=[...suggested].join('|');
 useEffect(()=>{const ids=signature.split('|').filter(Boolean);if(previous.current===null){previous.current=ids;if(value===undefined)onChange(reconcileRecurrences([],[],profile,responsible));return;}if(previous.current.join('|')!==signature){const before=previous.current;previous.current=ids;onChange(reconcileRecurrences(rules,before,profile,responsible,excluded.current));}},[signature,value,profile,responsible,onChange,rules]);
 const change=(id:string,key:string,val:JsonValue)=>onChange(rules.map(r=>r.modeloId===id?{...r,[key]:val}:r));
 return <section className="recurrence-review"><h3>Tarefas recorrentes e responsáveis</h3><p>As tarefas previstas para o regime e perfil vêm marcadas. Você pode desmarcar exceções e adicionar outras. Confira responsáveis e prazos internos antes de salvar.</p><label className="field">Buscar tarefa<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome ou departamento"/></label><button type="button" className="button button-secondary" onClick={()=>onChange(rules.map(r=>({...r,responsavelId:responsible})))} disabled={!responsible}>Atribuir selecionadas ao responsável do cliente</button>
 {TASK_MODELS.filter(m=>(m.nome+' '+m.departamento).toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))).map(m=>{const rule=rules.find(r=>r.modeloId===m.id);return <article key={m.id} style={{borderBottom:'1px solid #dfe7dd',padding:'16px 0'}}><label className="field-check"><input type="checkbox" checked={!!rule} onChange={e=>{excluded.current=e.target.checked?excluded.current.filter(id=>id!==m.id):[...excluded.current,m.id];onChange(e.target.checked?[...rules,{modeloId:m.id,periodicidade:m.periodicidade,responsavelId:responsible,diaVencimento:20,...(m.mes?{mes:m.mes}:{})}]:rules.filter(r=>r.modeloId!==m.id));}}/><strong>{m.nome}</strong> · {m.periodicidade}{suggested.has(m.id)?' · Prevista para o regime/perfil':''}</label>{rule&&<div className="form-grid"><label className="field">Responsável por {m.nome}<select required value={text(rule.responsavelId)} onChange={e=>change(m.id,'responsavelId',e.target.value)}><option value="">Selecione</option>{team.filter(t=>t.ativo!==false).map(t=><option key={t.id} value={t.id}>{text(t.nome)}</option>)}</select></label><label className="field">Dia do prazo<input required type="number" min="1" max="31" value={text(rule.diaVencimento)} onChange={e=>change(m.id,'diaVencimento',Number(e.target.value))}/></label>{m.periodicidade==='anual'&&<label className="field">Mês<input required type="number" min="1" max="12" value={text(rule.mes)} onChange={e=>change(m.id,'mes',Number(e.target.value))}/></label>}</div>}<details><summary>Como executar: {taskSteps(m.id,profile as Entity).length} passos</summary><ol>{taskSteps(m.id,profile as Entity).map(s=><li key={s.id}>{s.descricao}</li>)}</ol></details></article>})}</section>;
}

