import type { Entity, Stage, Step, RecurrenceRecommendation } from '../../types/domain';
export interface TaskModel { id: string; nome: string; departamento: string; periodicidade: 'mensal'|'trimestral'|'anual'; exigeProtocolo: boolean; passos: string[]; mes?: number }
const collectionSteps = ['Solicitar documentos ao cliente','Receber XMLs de entrada e saída','Receber extratos de todas as contas','Receber ponto e movimentações de pessoal','Receber notas de despesa e comprovantes','Conferir documentos contra o mês anterior','Cobrar documentos pendentes e registrar retorno','Resolver pendências ou registrar justificativa do responsável'];
const fiscalSteps = ['Importar XMLs de entrada e saída','Conferir notas com portais, cancelamentos e inutilizações','Escriturar entradas e saídas','Apurar encargos conforme regime','Conferir faturamento escriturado e declarado','Transmitir obrigações da competência','Enviar guias ao cliente','Registrar comprovante de envio'];
const payrollSteps = ['Solicitar movimentações de pessoal','Lançar movimentações no sistema','Conferir lançamentos','Conferir saúde, transporte, alimentação, horas extras, faltas e descontos','Conferir variação da folha contra o mês anterior','Transmitir o eSocial','Transmitir a DCTFWeb','Gerar FGTS Digital, DARF INSS e DARF IRRF','Enviar folha, holerites e guias','Registrar comprovante de envio'];
const accountingSteps = ['Solicitar extratos','Realizar lançamentos','Realizar conciliação contábil','Conferir caixa, bancos, fornecedores e clientes','Fechar balancete','Analisar resultado e variações','Gerar dashboard e relatório'];
const genericLegal = ['Conferir os dados e a aplicabilidade','Preparar e revisar a obrigação','Transmitir no sistema oficial','Anexar recibo e registrar protocolo','Registrar entrega ao cliente'];
function model(id:string,nome:string,departamento:string,periodicidade:TaskModel['periodicidade']='mensal',exigeProtocolo=false,passos:string[]=genericLegal,mes?:number):TaskModel { return {id,nome,departamento,periodicidade,exigeProtocolo,passos,...(mes?{mes}:{})}; }
export const TASK_MODELS: TaskModel[] = [
 model('conciliacao-bancaria','Conciliação bancária','Financeiro','mensal',false,['Solicitar extratos de todas as contas da competência','Conferir saldo inicial e final de cada conta','Relacionar movimentações aos documentos e lançamentos','Identificar duplicidades e valores sem identificação','Solicitar esclarecimentos e registrar pendências','Conferir saldos conciliados e salvar relatório']),
 model('contas-pagar','Revisão de contas a pagar','Financeiro','mensal',false,['Receber relação de compromissos e comprovantes','Conferir fornecedor, vencimento, valor e duplicidades','Classificar despesas e centros de custo','Separar pendências para aprovação do cliente','Atualizar previsões e registrar entrega do relatório']),
 model('contas-receber','Revisão de contas a receber','Financeiro','mensal',false,['Conferir títulos e vendas da competência','Relacionar recebimentos aos extratos','Identificar atrasos e pagamentos parciais','Preparar relação de pendências para o cliente','Registrar retorno e atualizar a previsão de recebimento']),
 model('ferias','Programação de férias','Pessoal','mensal',false,['Conferir períodos aquisitivos e programação existente','Listar períodos que precisam de planejamento','Solicitar ao cliente datas e confirmação dos empregados','Revisar programação com o responsável de pessoal','Registrar decisões e criar demandas individuais necessárias']),
 model('validade-documentos','Revisão de licenças e certificados','Administrativo','mensal',false,['Conferir documentos e datas de validade cadastrados','Relacionar documentos próximos do vencimento','Confirmar necessidade de renovação com o responsável','Solicitar documentos e agendar providências','Registrar acompanhamento e atualizar o cadastro após comprovação']),
 model('cadastro-cliente','Revisão cadastral do cliente','Administrativo','trimestral',false,['Confirmar contatos e responsável pelo envio de documentos','Revisar atividades, quadro de pessoal e serviços contratados','Conferir canais de atendimento e acessos necessários','Revisar recorrências e responsáveis com a equipe','Registrar alterações confirmadas e pendências']),
 model('coleta','Coleta de documentos','Administrativo','mensal',false,collectionSteps),model('fiscal','Fechamento Fiscal','Fiscal','mensal',true,fiscalSteps),model('folha','Fechamento de Folha','Pessoal','mensal',true,payrollSteps),model('contabil','Fechamento Contábil','Contábil','mensal',false,accountingSteps),
 model('prolabore','Fechamento de pró-labore','Pessoal','mensal',true,payrollSteps),model('das-mei','DAS-MEI','Fiscal','mensal',true),model('dasn','DASN-SIMEI','Fiscal','anual',true),model('pgdas','PGDAS-D e DAS','Fiscal','mensal',true),model('defis','DEFIS','Fiscal','anual',true),
 model('pis-cofins','PIS e COFINS','Fiscal','mensal',true),model('irpj-csll','IRPJ e CSLL','Fiscal','trimestral',true),model('efd-contribuicoes','EFD Contribuições','Fiscal','mensal',true),model('ecf','ECF','Contábil','anual',true),model('ecd','ECD','Contábil','anual',true),
 model('esocial','eSocial','Pessoal','mensal',true),model('fgts','FGTS Digital','Pessoal','mensal',true),model('dctfweb','DCTFWeb','Pessoal','mensal',true),model('decimo-1','13º primeira parcela','Pessoal','anual',false,genericLegal,11),model('decimo-2','13º segunda parcela','Pessoal','anual',false,genericLegal,12),
 model('reinf','EFD-Reinf','Fiscal','mensal',true),model('efd-icms','EFD ICMS/IPI','Fiscal','mensal',true),model('gia','GIA conforme UF','Fiscal','mensal',true),model('iss','ISS','Fiscal','mensal',true),model('declaracao-servicos','Declaração municipal de serviços','Fiscal','mensal',true),
 model('gerencial','Relatório gerencial','Contábil','mensal',false,['Conferir base financeira','Preparar relatório gerencial','Analisar e registrar recomendações','Registrar entrega ao cliente']),model('fator-r','Análise de Fator R','Fiscal','mensal',false,['Confirmar dados e período de cálculo','Calcular e revisar o Fator R','Registrar diagnóstico e ação proposta']),model('cnds','Monitoramento de CNDs','Fiscal','mensal',false,['Consultar certidões nas fontes oficiais','Registrar validade e pendências','Comunicar ações necessárias']),
 model('planejamento','Planejamento tributário','Fiscal','anual',false,['Consolidar dados fiscais','Comparar cenários com normas vigentes','Revisar premissas','Apresentar e registrar diagnóstico']),model('resultados','Reunião de resultados','Contábil','mensal',false,['Agendar reunião de resultados','Apresentar análise','Registrar ata e encaminhamentos']),model('precificacao','Análise de precificação','Financeiro','trimestral',false,['Conferir custos e volume','Analisar margem por produto','Preparar proposta de preços','Registrar apresentação']),model('balanco','Balanço patrimonial e demonstrações','Contábil','anual',false,['Concluir conferências anuais','Gerar balanço e DRE do exercício','Gerar mutações do patrimônio líquido quando aplicável','Revisar e entregar demonstrações']),
];
export function taskSteps(modelId: string, cliente: Pick<Entity,string> = {} as Entity): Step[] {
 const template=TASK_MODELS.find(item=>item.id===modelId); if(!template) throw new Error('Modelo de tarefa não encontrado.');
 const descriptions=[...template.passos];
 if(modelId==='contabil') descriptions.push(cliente.plano==='Estratégico'?'Agendar reunião, apresentar resultados e registrar ata':'Enviar dashboard e análise ao cliente','Registrar envio ou realização da reunião');
 if(modelId==='fiscal') {
  if(cliente.regime==='Simples Nacional') descriptions.splice(3,0,'Segregar receitas e conferir anexo e Fator R quando aplicável');
  if(['Comércio','Indústria'].includes(String(cliente.atividade))) descriptions.splice(2,0,'Conferir ICMS-ST e DIFAL quando aplicáveis');
  if(cliente.retencoes===true) descriptions.splice(4,0,'Conferir retenções de ISS, IRRF, INSS, PIS, COFINS e CSLL');
 }
 return descriptions.map((descricao,index)=>({id:`${modelId}-${index+1}`,descricao,obrigatorio:true,concluido:false,natureza:'marcar'}));
}
export function recommendRecurrences(cliente: Record<string, unknown>): RecurrenceRecommendation[] {
 const ids=new Set(['coleta','fiscal','contabil','balanco']);
 const regime=String(cliente.regime??''); const mei=regime==='MEI'||cliente.enquadramento==='MEI';
 if(mei) ['das-mei','dasn'].forEach(id=>ids.add(id));
 else if(regime==='Simples Nacional') ['pgdas','defis'].forEach(id=>ids.add(id));
 else if(['Lucro Presumido','Lucro Real'].includes(regime)) ['pis-cofins','irpj-csll','efd-contribuicoes','ecf','ecd'].forEach(id=>ids.add(id));
 if(Number(cliente.funcionarios??0)>0) ['folha','esocial','fgts','dctfweb','decimo-1','decimo-2'].forEach(id=>ids.add(id));
 else if(cliente.proLabore===true || Number(cliente.proLabore)>0) ['prolabore','esocial','dctfweb'].forEach(id=>ids.add(id));
 if(cliente.retencoes===true) ids.add('reinf');
 if(['Comércio','Indústria'].includes(String(cliente.atividade))&&Boolean(cliente.inscricaoEstadual)) ['efd-icms','gia'].forEach(id=>ids.add(id));
 if(cliente.atividade==='Serviços') ['iss','declaracao-servicos'].forEach(id=>ids.add(id));
 if(['Mentor','Estratégico'].includes(String(cliente.plano))) ['gerencial','fator-r','cnds','planejamento'].forEach(id=>ids.add(id));
 if(cliente.plano==='Estratégico') ['resultados','precificacao'].forEach(id=>ids.add(id));
 return TASK_MODELS.filter(item=>ids.has(item.id)).map(item=>({modeloId:item.id,nome:item.nome,departamento:item.departamento,periodicidade:item.periodicidade,exigeProtocolo:item.exigeProtocolo,confirmacaoNecessaria:true}));
}
export const PROCESS_TEMPLATES: {id:string;nome:string;blocos:{nome:string;itens:string[]}[]}[] = [
 {id:'abertura',nome:'Abertura de empresa',blocos:[
 {nome:'Dados pessoais dos sócios',itens:['Nome completo','CPF','RG','Estado civil','Endereço residencial','E-mail e telefone']},
 {nome:'Dados da empresa',itens:['Nome empresarial e fantasia','Endereço comercial','CNAEs','Regime tributário desejado','Capital social','Participação societária']},
 {nome:'Documentação',itens:['Documentos pessoais dos sócios','Comprovante de endereço da empresa','Contrato social, se aplicável','Número do IPTU','Consulta de viabilidade']},
 {nome:'Análise e planejamento',itens:['Verificar atividade permitida no endereço','Consultar viabilidade na Junta','Definir regime tributário','Elaborar contrato social']},
 {nome:'Registro',itens:['Protocolo na Junta Comercial','CNPJ na Receita Federal','Inscrição municipal','Inscrição estadual, se aplicável']},
 {nome:'Alvarás',itens:['Bombeiros','Provisório','Sanitário','Funcionamento','AMMA, quando aplicável']},
 {nome:'SEFAZ e Prefeitura',itens:['Cadastrar DTE SEFAZ','Habilitar emissão de notas','Cadastrar CSC, se comércio','Solicitar usuário para consulta bancária']},
 {nome:'Finalização',itens:['Certificado digital, se necessário','Cadastro eSocial, quando aplicável','Abertura de conta PJ','Assinatura e entrega de documentos','Encaminhar para integração']}]},
 {id:'desenquadramento',nome:'Desenquadramento de MEI para LTDA',blocos:[
 {nome:'Portal do Simples',itens:['Acessar portal','Solicitar desenquadramento','Guardar comprovante']},{nome:'Junta',itens:['Acessar sistema','Registrar atualização','Aguardar retorno']},{nome:'Viabilidade',itens:['Solicitar viabilidade','Registrar deferimento']},{nome:'DBE',itens:['Acessar Coletor Nacional','Preencher alteração','Gerar protocolo e acompanhar']},{nome:'FCN',itens:['Acessar Junta','Preencher FCN']},{nome:'Taxa',itens:['Gerar guia','Enviar ao cliente','Confirmar compensação']},{nome:'Contrato social',itens:['Redigir sócios, capital e administração','Conferir objeto social','Consolidar contrato']},{nome:'Assinatura',itens:['Gerar link de assinatura','Confirmar assinatura']},{nome:'Análise da Junta',itens:['Acompanhar análise','Baixar contrato registrado']},{nome:'Prefeitura',itens:['Atualizar cadastro municipal','Verificar inscrição e taxas']},{nome:'SEFAZ',itens:['Verificar aplicabilidade','Atualizar inscrição estadual','Regularizar cadastro ICMS','Emitir documentos fiscais']}]},
 {id:'endereco',nome:'Alteração de endereço em Goiânia',blocos:[
 {nome:'Documentos do novo endereço',itens:['Comprovante de endereço','IPTU','Contrato de aluguel ou escritura','Alvará do prédio','Bombeiros do prédio','Habite-se','Número oficial','Uso do solo','Documentos específicos do ramo']},{nome:'Uso do solo',itens:['Verificar atividade','Solicitar análise','Informar encaminhamento AMMA ao parceiro','Salvar deferimento']},{nome:'Cobrança inicial',itens:['Calcular honorários conforme catálogo','Cobrar 50%','Confirmar pagamento']},{nome:'Início',itens:['Viabilidade JUCEG','DBE','FCN','Gerar DARE','Enviar taxa']},{nome:'Contrato',itens:['Redigir alteração','Enviar para revisão','Enviar assinatura','Confirmar pagamento da taxa']},{nome:'Protocolo',itens:['Protocolar documentos assinados','Acompanhar deferimento','Baixar registro','Enviar autenticado ao cliente']},{nome:'Pós-Junta',itens:['Atualizar Prefeitura','Atualizar SEFAZ, se aplicável','Solicitar novo alvará','Encaminhar Bombeiros ou AMMA','Informar conclusão']}]},
 {id:'baixa',nome:'Baixa de CNPJ',blocos:[{nome:'Pré-requisitos',itens:['Verificar certificado digital válido','Confirmar honorários','Receber 50% de entrada']},{nome:'Execução',itens:['Conferir pendências','Protocolar baixa','Salvar comprovação de baixa']},{nome:'Finalização',itens:['Receber saldo de 50%','Entregar documentação ao cliente']}]},
 {id:'onboarding',nome:'Onboarding de cliente',blocos:[
 {nome:'Contrato',itens:['Confeccionar contrato','Cadastrar contrato na assinatura digital','Enviar para assinatura','Confirmar contrato assinado','Salvar contrato na pasta do cliente']},{nome:'Acessos e sistemas',itens:['Fazer procuração e-CAC','Cadastrar em Alterdata, eContador, NF Stock e Veri','Cadastrar no sistema de cobrança']},{nome:'Integração',itens:['Agendar reunião de onboarding','Enviar boas-vindas e manuais','Agendar treinamento']}]},
 {id:'alvara',nome:'Alvará ou licença',blocos:[{nome:'Preparação',itens:['Verificar exigência e documentação','Conferir cadastro do cliente','Conferir taxas']},{nome:'Execução',itens:['Protocolar solicitação','Acompanhar análise','Resolver exigências']},{nome:'Entrega',itens:['Anexar licença emitida','Informar validade','Registrar entrega ao cliente']}]},
 {id:'certificado',nome:'Certificado digital',blocos:[{nome:'Preparação',itens:['Conferir titular e documentos','Confirmar modalidade e agendamento']},{nome:'Emissão e entrega',itens:['Confirmar emissão','Armazenar arquivo em local privado','Informar validade','Registrar entrega ao responsável']}]}];
export function createProcessStages(templateId: string): Stage[] {
 const template=PROCESS_TEMPLATES.find(item=>item.id===templateId); if(!template) throw new Error('Template de processo não encontrado.');
 return template.blocos.map((block,index)=>({id:`${templateId}-etapa-${index}`,nome:block.nome,itens:block.itens.map((descricao,i)=>({id:`${templateId}-${index}-${i}`,descricao,obrigatorio:true,concluido:false,natureza:'marcar'}))}));
}
